[workspace]
authors = ["Lucas Colley <lucas.colley8@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
description = "Lucas Colley's Personal Website"
name = "lucascolley.github.io"
platforms = ["osx-arm64"]

[tasks]
preview = { cmd = "hugo server -D -O", cwd = "lucascolley" }

[dependencies]
hugo = ">=0.150.1,<0.151"
