baseURL = "https://lucascolley.github.io"
languageCode = "en-GB"
title = "Lucas Colley"
theme = "PaperMod"

[params]
defaultTheme = "auto"

socialIcons = [
    { name = "email", url = "mailto:lucas.colley8@gmail.com" },
    { name = "linkedin", url = "https://www.linkedin.com/in/lucascolley0/" },
    { name = "github", url = "https://github.com/lucascolley" },
] # Shown on the home page

# Configure the home page
[params.profileMode]
enabled = true

# Site-wide navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "about"
title = "about"
url = "/about/"

[[menu.main]]
weight = 2
identifier = "music"
name = "music"
title = "music"
url = "/music/"
