baseURL = "https://lucascolley.github.io"
languageCode = "en-GB"
title = "Lucas Colley"
theme = "PaperMod"

[params]
defaultTheme = "auto"

# Shown on the home page
socialIcons = [
    { name = "github", url = "https://github.com/lucascolley" },
]

# Configure the home page
[params.profileMode]
enabled = true

# Site-wide navigation
[[menu.main]]
weight = 1
identifier = "about"
name = "about"
title = "about"
url = "/about/"
